pschatzmann/ESP32-A2DP

README.md
src/BluetoothA2DPSink.cpp
src/BluetoothA2DPSink.h

Thank you for setting this up and sharing it!
I needed to access the incoming packets for analysis, so I added a new callback.
I also didn't see the data_received callback on the readme, so I added notes for both.

Add packet access for receiver and document packet received callback

---

src/BluetoothA2DPSource.h
src/SoundData.h

Needed if building on a Linux workstation where the correct case is required.

Fix case for Arduino.h include

---

src/BluetoothA2DPSink.cpp

Solving #26 by only automatically reconnecting when previous disconnect was not clean (e.g. power loss).

No auto reconnect after clean disconnect

---

src/BluetoothA2DPSink.cpp

If bluedroid was initialized previously for a different purpose, I believe we shouldn't fail the initialization of the A2DP sink. I added a couple of checks to properly initialize it.
In the A2DP source, I the only place that bluedroid is initialized is right after a reset, therefore such a check is not necessary.

Improved init_bluetooth checks, in case bluedroid was already initialized elsewhere

---

src/BluetoothA2DPSink.cpp

This allows the stream reader to modify the stream (e.g. by a DSP) prior sending it to i2s

Send to i2s output after calling the stream reader

---

src/BluetoothA2DPSink.cpp

New Feature: Number of Tracks in Playlist and Current Track-Nr. added to Metadata
Supported with most mobile Players (in Android)

Tracknumber and TrackCount added to Metadata

---

src/BluetoothA2DPSink.cpp
src/BluetoothA2DPSink.h

Add a wrapper to call [`esp_a2d_sink_disconnect`](https://docs.espressif.com/projects/esp-idf/en/v4.2-beta1/esp32/api-reference/bluetooth/esp_a2dp.html#_CPPv423esp_a2d_sink_disconnect13esp_bd_addr_t) allowing you to disconnect the currently connected device. 
I am not sure if the the commented section is required, it works in my simple case - but I must admit I don't have sufficient knowledge here..

Add method to disconnect current connection

---

src/BluetoothA2DPSink.cpp

- Convert between LE and BE
- Consistently use 127 as max volume
- Implement non-linear curve for volume scaling
This probably also solves https://github.com/pschatzmann/ESP32-A2DP/issues/88
@tv4you2016 could you check if these changes also work fine in your case?
@pschatzmann I'm not sure if these changes make sense for every case but at least for me, the volume control now works perfectly fine
- the non-linear curve allows smaller volume steps in on lower volumes.
- not converting between LE and BE was simply wrong in my case
- currently, get_volume returns max 100 while set_volume takes 127. WIth this change, the max volume is always 127.

Improve volume control

---

src/BluetoothA2DPSink.cpp

After failed authentication attempt, code resets received pin_code and state
to 0 / Undefined. 
Without this change, after failed authenication
the BluetoothA2DPSink::pin_code()  still returns
the code and the application will not be able
to easily detect that no authentication is in
progress by checking pin_code() == 0.
Only other way to achieve this without code change 
would be to subclass BluetoothA2DPSink and provide
app_gap_callback but that seems to be not really appropriate.
BTW, thanks for the code, made making a bluetooth speaker a breeze.
If you are interested, I could provide an example for the examples folder which demonstrates how to use
this to build a simple bluetooth sink which accepts pairing request only after pressing a key.
EDIT: Of course, …

Enable easy detection of failed authentication

---

CMakeLists.txt

`src/SoundData.cpp` is currently missing from `idf_component_register(SRCS ...`. It isn't used in the IDF example which is why that works but throws an `undefined reference to SoundData::doLoop()` error during the `Linking CXX executable` step when running the `bt_music_sender` example. PR fixes this issue.

Add missing SRC for idf

---

src/BluetoothA2DPSink.cpp

Suspended wasn't reaching the call-back since ESP_A2D_AUDIO_STATE_REMOTE_SUSPEND = 0 while is seen as false in the statement below
`if (audio_state_callback!=nullptr && audio_state){`

Fixed the case of suspend

---

src/BluetoothA2DPSource.cpp

These lines made it so this code would not pair with a lot of Bluetooth speakers:
/* search for device with MAJOR service class as "rendering" in COD */
if (!esp_bt_gap_is_valid_cod(cod) ||
!(esp_bt_gap_get_cod_srvc(cod) & ESP_BT_COD_SRVC_RENDERING)) {
return;
}
I modified the code so that it only validates against MAJOR DEVICE being AV. I also removed the esp_bt_gap_is_valid_cod check because I found that some of my bluetooth speakers did not pass that check, but they still were detected as valid AV devices. The rest of the changes are just clean up and a slight restructure of the filter_inquiry_scan_result function and ESP_LOG calls
/* search for device with MAJOR DEVICE class as "Audio/Visual" in COD */
if ((esp_bt_gap_get_cod_major_dev(cod) == ESP_BT_COD_MAJOR_DEV_AV))
{

Fixed Bluetooth Source pairing so it works with more devices

---

CMakeLists.txt
src/config.h

The version check doesn't work unless it's performed after declaration of the esp-idf header.

Fix esp-idf version check

---

src/BluetoothA2DPCommon.cpp
src/BluetoothA2DPCommon.h
src/BluetoothA2DPSink.cpp

Hello,
I'm working with TI's [(TAS5805M)](https://www.ti.com/lit/ds/symlink/tas5805m.pdf?ts=1659808432711) amplifier. From reading section 7.5.3.1 I have to bring the PDN pin high and then wait 5ms before enabling I2S. After the I2S is enabled I can send I2C commands to finish the startup process.
To do this I have modified the code to create a second audio_state_callback function that is called after I2S is enabled.

Added support for a post I2S init callback.

---

src/BluetoothA2DPSink.cpp
src/BluetoothA2DPSink.h

I had a need to get sound data before changing the volume level, but without changing the library code, I could not do this. Therefore, I suggest also adding a `raw_stream_reader` for such cases.
PS: I am developing a color music device in which I convert the received audio samples to amplitudes using the fast fourier transform. You may ask, what is the need for processing samples that do not change in volume? I will answer, this is necessary for light modes with quiet parts in the audio composition, because depending on the volume, the algorithm can confuse a quiet place in the music with a low device volume.
I think the added functionality will also be useful when adding an equalizer, with direct and inverse Fourier transform, since the calculation at higher volume levels will occur …

add raw_stream_reader

---

src/BluetoothA2DPSink.cpp

Failure messages for ESP_AVRC_PT_CMD_STATE_PRESSED and ESP_AVRC_PT_CMD_STATE_RELEASED were mismatched.

Fix typo at BluetoothA2DPSink::execute_avrc_command

---

README.md

The import statement may fail to compile with some compilers.
(Is this for compatibility?)

chore: fix examples in README

---

README.md
examples/bt_music_receiver_playing_status_callbacks/bt_music_receiver_playing_status_callbacks.ino
examples/bt_music_receiver_with_metadata/bt_music_receiver_with_metadata.ino
src/BluetoothA2DPSink.cpp
src/BluetoothA2DPSink.h

After lots of digging around, I realized that rather than mess with ESP_AVRC_RN_PLAY_POS_CHANGED and esp_avrc_ct_send_register_notification_cmd and esp_avrc_rn_param_t.play_pos, we have an example implementation of a callback all ready to go with `avrc_rn_playstatus_callback(event_parameter->playback)` just a few lines above, and indeed a `av_play_pos_changed()` function ready to go, so all that's left is to make a `avrc_rn_play_pos_callback()` and we can easily display song progress with the same API we're already used to.
In implementing a song progress indicator I also ran into the confusing situation that ESP_AVRC_MD_ATTR_PLAYING_TIME is not just milliseconds of total song time but *milliseconds stored as text in a `char*`* which seemed to cause plenty of confusion as well, so I added …

Add play_pos callback with examples and README, also playing_time clarification

---

src/BluetoothA2DPSource.cpp

Added in compile macros to change the code based on IDF version support of rsp_code.
rsp_code is not supported before idf version 5.1

added in conditional logic based on ESP_IDF version for rsp_code support

---

src/BluetoothA2DPSource.cpp
src/BluetoothA2DPSource.h

Added in a callback that is similar to the SSID_callback. The new callback allows you to be notified when the Discovery Mode changes.

Added in Bluetooth Discovery Mode callback
